server:
  port: 8081
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/notification"
    username: "postgres"
    password: "password"
  jpa:
    properties:
       hibernate:
        jdbc:
          lob:
             non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true