spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/customer"
    username: "postgres"
    password: "password"
    initialization-mode: always
  cloud:
    refresh:
      refreshable: none

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false

