
language: java
jdk: oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN: "5713d185-9a8f-45bc-84e7-d5d35f8ceb3b"
cache:
  directories:
    - $HOME/.m2
services:
  - memcached